### ISSUE TITLE
Status is not correct evaluated

### ISSUE THREAD

**Issue by blaubaer** [levertonai/kubor#8]
**Environment**
* OS: `linux`
* Arch: `amd64`
* Version: `0.4.7`

**Steps to reproduce the behavior**
1. Have a project with a configuration file for a deployment like:
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{.ArtifactId}}
      namespace: {{.GroupId}}
    ...
    ```
2. Apply it the first time to the target cluster.
3. Ensure that it already exists there.
4. Apply it again with `kubor apply`.

**Observed behavior**
1. `kubor apply` reported instantly the success of the apply (no wait) but a `kubectl get pods` is showing that the related pods are still starting.

**Expected behavior** 
1. When `kubor apply` report a success of the apply directly after it a `kubectl get pods` shows all minimum required pods are up.
